define([
	"jmpress/core",
	"jmpress/near",
	"jmpress/transform",
	"jmpress/active",
	"jmpress/circular",
	"jmpress/start",
	"jmpress/hash",
	"jmpress/viewport",
	"jmpress/mobile",
	"jquery.jmpress.story"
]);
