define([
	"jquery.jmpress.core",
	"jquery.jmpress.near",
	"jquery.jmpress.transform",
	"jquery.jmpress.active",
	"jquery.jmpress.circular",
	"jquery.jmpress.start",
	"jquery.jmpress.hash",
	"jquery.jmpress.viewport",
	"jquery.jmpress.mobile",
	"jquery.jmpress.step"
]);
