DROP TABLE IF EXISTS ws_invite CASCADE;
DROP TABLE IF EXISTS invite_sequences CASCADE;

DROP TABLE IF EXISTS ws_facebook CASCADE;
DROP TABLE IF EXISTS facebook_sequences CASCADE;

DROP TABLE IF EXISTS ws_story CASCADE;
DROP TABLE IF EXISTS story_sequences CASCADE;

DROP TABLE IF EXISTS ws_meta CASCADE;