DROP TABLE IF EXISTS ws_invite CASCADE;
DROP TABLE IF EXISTS invite_sequences CASCADE;

DROP TABLE IF EXISTS ws_user CASCADE;
DROP TABLE IF EXISTS user_sequences CASCADE;

DROP TABLE IF EXISTS ws_facebook CASCADE;

DROP TABLE IF EXISTS ws_story CASCADE;
DROP TABLE IF EXISTS story_sequences CASCADE;

DROP TABLE IF EXISTS ws_meta CASCADE;

DROP TABLE IF EXISTS ws_chapter CASCADE;
DROP TABLE IF EXISTS chapter_sequences CASCADE;

DROP TABLE IF EXISTS ws_section CASCADE;
DROP TABLE IF EXISTS section_sequences CASCADE;